project6/ecommerce/cart/urls.py
from . import views
from django.urls import path
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

project6/ecommerce/ecomapp/urls.py
from . import views
from django.urls import path
app_name = 'ecomapp'

urlpatterns = [
    path('', views.allProductCat, name='allProductCat'),
    path('<slug:c_slug>/', views.allProductCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodDetail, name='prod_Cat_Det')
]

project6/ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/', include('ecomapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('my_cart/', include('my_cart.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project6/ecommerce/my_cart/urls.py
from . import views
from django.urls import path
app_name = 'my_cart'

urlpatterns = [
    path('', views.prodDetail, name='prod_Cat_Det')
]

project6/ecommerce/search_app/urls.py
from django.urls import path
from .  import views

app_name= 'search_app'
urlpatterns=[
    path('', views.SearchResult,name='SearchResult')
]

project6/ecommerce/cart/models.py
from django.db import models
from ecomapp.models import product
from django.urls import reverse

# Create your models here.d
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added= models.DateField(auto_now_add=True)


    class Meta:
        db_table= 'Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    prod = models.ForeignKey(product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity= models.IntegerField()
    active= models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'


    def sub_total(self):
        return self.prod.price * self.quantity

    def __str__(self):
        return self.prod

project6/ecommerce/cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request, product_id):
    prod = product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart= Cart.objects.create(cart_id=cart_id(request))
        cart.save(),
    try:
        cart_item=CartItem.objects.get(prod=prod, cart=cart)
        if cart_item.quantity < cart_item.prod.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            prod=prod,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items= CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            # total += cart_item.sub_total
            total += (cart_item.quantity * cart_item.prod.price)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def delete_item(request, item_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    prod = get_object_or_404(product, id=item_id)
    cart_item = CartItem.objects.get(prod=prod, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')
    # # Get the cart by its identifier or return a 404 error if it doesn't exist
    # CartItem.objects.get(prod=item_id).delete()
    # # cart.delete()
    # return render(request, 'cart.html')
def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    prod=get_object_or_404(product,id=product_id)
    cart_item=CartItem.objects.get(prod=prod,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

project6/ecommerce/templates/base.html
{% load static %}
<html lang="en">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'custom.css' %}">
<link rel="stylesheet" href="{% static 'drop.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}


        <script src="{% static 'js/popper.min.js' %}" ></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </div>
<!--{% include 'footer.html' %}-->
</body>
</html>

project6/ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'custom.css' %}">

{% block metadescription %}
    product cart
{% endblock %}
{% block title %}
        {{ product.name }} - Cart
{% endblock %}

{% block content %}
<div class="container">
    {% if not cart_items %}


        <div class="text-center"><br>
            <h4 class="text-center my_title">Your Shopping cart is empty</h4><br>
            <a href="{% url 'ecomapp:allProductCat' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Please Click Here</a>

        </div>
    {% else %}
        <div>
            <div class="text-left"><br>
                <h5 class="text-center my_title">Your Shopping cart</h5
                ><br>
            </div>
        </div>
    {% endif %}

    <div class="row-max-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

        </div>
        <div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

            </div>
        </div>
    </div>

    <div style="width: 100%; height: 650px;">
        <div style=" width: 50%; height: 550px; float:left;">
            <table class="table my_custom_table">
                   <thead class="thead-light">
                        <tr>
                            <th colspan="5" class="text-center my_title">Your Items</th>
                        </tr>
                   </thead>
                    <tbody>
                        {% for cart_item in cart_items %}

                            <tr>
                                <td class="text-lf">
                                    <h4>{{cart_item.prod.name}}</h4><br>
<!--                                    SKU: {{cart_item_prod.id}}<br>-->
                                </td>
                                {% if cart_item.quantity < cart_item.prod.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.prod.id %}" class="custom_a"> <i class="fa-solid fa-plus"></i></a>
                                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <a href="{% url 'cart:cart_remove' cart_item.prod.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <a href="{% url 'cart:delete_item' cart_item.prod.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        <a href="{% url 'cart:cart_remove' cart_item.prod.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        <a href="{% url 'cart:delete_item' cart_item.prod.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>
                                    </td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>
                                    <a href="cart_item.prod.get_absolute_url"></a><img src="{{cart_item.prod.image.url}}" alt="" class="float-left rounded custom_image">
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <h6>&nbsp;&nbsp;&nbsp;Price&nbsp;&nbsp;:${{cart_item.prod.price}}<br>
                                    &nbsp;&nbsp;&nbsp;Qty &nbsp;&nbsp;&nbsp;: {{ cart_item.quantity}} x $ {{cart_item.prod.price}}
                                     &nbsp;&nbsp;&nbsp;Total  &nbsp;:${{cart_item.sub_total}}.....{{counter}}</h6>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
        <div style=" width:50%; height: 550px; float:left;">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                      <th scope="col" class="text-center my_title">Checkout</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Please review your shopping cart item before proceeding with the order payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total is :<strong>{{ total }}</strong>
                    </td>
                </tr>
                </tbody>
                </table>
            <a class="btn btn-primary" href="{% url 'ecomapp:allProductCat' %}" role="button"> Continue Shoping</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


            <a class="btn btn-success" href="{% url 'ecomapp:allProductCat' %}" role="button">Goto Payment</a>
        </div>
    </div>
</div>
{% endblock %}

project6/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'custom.css' %}">
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to my store
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - ABC Store
    {% else %}
        Our new collection
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}


            <div>
                <div class="alert alert-dark" role="alert">
                    <a href="{% url 'ecomapp:allProductCat' %}"
                          class="badge badge-secondary"
                          style="text-center">Our Product Collections</a>
                </div>
            </div>
    {% endif %}
    <div>
        {% if category %}
            <div>
                <h1 class="display-3">{{category.name}}</h1>
                <p>{{category.description}}</p>
            </div>
        {% else %}<br>
        <div>
                <img src="{% static 'image/homebanner.png' %}"  width="100%" alt="Our products">

                <h3>Our Product Collection</h3>
                <nav class="navbar navbar-light bg-light">
                    <span class="container">
                        <p class="font-weight-light">When using Lorem Ipsum for creating dummy content for your newly created website,
                        you can select the text formats you want from the tool. Like, words, sentences,
                        or paragraphs. Then, you can select whether you want HTML markup in your dummy
                        content or not Then, you can choose the number of words and paragraphs for your
                        dummy content and execute the plan accordingly. You can use this tool at incrementors.</p>
                </span>
            </nav>


        </div>
        {% endif %}
    </div>
    <div class="row">
        {% for product in products %}
        <div class="col-md-4">
            <div class="shadow-card" style="width: 18rem;">
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p>{{product.price}}</p>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="{{product.get_url}}" class="btn btn-primary">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm> {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

project6/ecommerce/templates/footer.html
{% load static %}

<div>

    <p>&copy; ShopCart pvt ltd.All rights Reserved</p>


</div>

project6/ecommerce/templates/header.html
{% load static %}

<header>
    <center>
        <div>
            <img src="{% static 'image/homebanner.png' %}"  width="100%" alt="Our products">
        </div>
    </center>
</header>

project6/ecommerce/templates/navbar.html
{% load static %}

<link rel="stylesheet" href="{% static 'drop.css' %}">
<div class="navbar">
        <div class="logo">VK WOOD</div>
        <ul class="menu">
            <li><a href="{% url 'ecomapp:allProductCat' %}">Home</a></li>
            <li class="dropdown">
                <a href="#">Category</a>
                <ul class="dropdown-content">
                    {% for cat in links %}
                        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li><a href="#">About Us</a></li>
            <li><a href="{% url 'my_cart:prod_Cat_Det' %}">my cart</a></li>

            <li><a href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a></li>


        </ul>
        <div class="search-bar">
            <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get">
            {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>

project6/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
        {{ product.name }} - ABC Store
{% endblock %}
{% block content %}

<div class="card" style="width: 18rem;">
  <img src="{{product.image.url}}" alt="{{product.name}}">
  <div class="card-body">
    <h5 class="card-title">{{product.name}}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <ul class="list-group list-group-flush">

    <li class="list-group-item">${{product.price}}</li>
  </ul>
  <div class="card-body">
      {% if product.stock <= 0 %}
            <a href="#" class="card-link">Out of stock</a>
      {% else %}
            <a class="btn btn-primary" href="{% url 'cart:add_cart' product.id %}" role="button">Add To Cart</a>
      {% endif %}


  </div>
</div>
{% endblock %}

project6/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    product search
{% endblock %}
{% block title %}
        {{ product.name }} - search
{% endblock %}
{% block content %}
     <div class="alert alert-dark" role="alert">
         <a href="{% url 'ecomapp:allProductCat' %}"
            class="badge badge-secondary"
            style="text-center">You have search for :<b>"{{query}}"</b></a>
     </div>

<!--    <div>-->
<!--        <div class="row">-->
<!--            {% for product in products %}-->
<!--                <div class="col-md-4">-->
<!--                    <div class="card" style="width: 18rem;">-->
<!--                        <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>-->
<!--                        <div class="card-body">-->
<!--                            <h5 class="card-title">{{product.name}}</h5>-->
<!--                            <p>{{product.price}}</p>-->
<!--                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--                            <a href="#" class="btn btn-primary">Go somewhere</a>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            {% empty %}-->
<!--            <div class="row mx-auto">-->
<!--                <p class="text-center my_search_text">0 result found</p>-->
<!--            </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<div class="row">
        {% for product in products %}
        <div class="col-md-4">
            <div class="shadow-card" style="width: 18rem;">
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p>{{product.price}}</p>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm> {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}